"""Build the JSON-configured VirtualFG producer with a Linux C++17 compiler."""
from pathlib import Path
import argparse
import os
import re
import subprocess

ROOT = Path(__file__).resolve().parent
OUTPUT = ROOT.parents[1] / "externals" / "virtualfg"


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--debug", action="store_true")
    args = parser.parse_args()
    header = (ROOT / "GenTL_v1_6.h").read_text()
    source = (ROOT / "virtualfg.cpp").read_text()
    exports = ["// Generated by build.py. Do not edit.", 'namespace GenTL { extern "C" {']
    for name, signature in re.findall(r"GC_API\s+(\w+)\s*\(([^;]*?)\)\s*;", header):
        parameters = [] if signature.strip() == "void" else signature.split(",")
        names = [re.search(r"(\w+)\s*$", value).group(1) for value in parameters]
        call = "impl_" + name
        if re.search(r"\b" + call + r"\s*\(", source):
            action = f"{call}(lock" + (", " + ", ".join(names) if names else "") + ");"
        else:
            action = "fail(GC_ERR_NOT_IMPLEMENTED, \"Optional function is not implemented\");"
        exports.append(f'''GC_API {name}({signature}) {{
    using namespace vfg;
    Lock lock(mutex);
    try {{ {action} return GC_ERR_SUCCESS; }}
    catch (const Fault& e) {{ last_code = e.code; last_text = e.text; return e.code; }}
    catch (const std::bad_alloc&) {{ last_code = GC_ERR_OUT_OF_MEMORY; last_text = "Out of memory"; return last_code; }}
    catch (...) {{ last_code = GC_ERR_ERROR; last_text = "Unexpected producer error"; return last_code; }}
}}''')
    exports.append("}}")
    (ROOT / "exports.inc").write_text("\n".join(exports) + "\n")
    command = [os.environ.get("CXX", "g++"), "-std=c++17", "-shared", "-fPIC", "-pthread",
               "-fvisibility=hidden", "-Wl,-z,defs", "-Wl,-Bsymbolic", "-Wall", "-Wextra",
               "-Wno-unused-parameter", "-O0" if args.debug else "-O2"]
    if args.debug:
        command.append("-g")
    # Publish only a successful build; never truncate a CTI that is loaded.
    OUTPUT.mkdir(parents=True, exist_ok=True)
    temporary = OUTPUT / "VirtualFG.cti.build"
    command += ["-I", str(ROOT / "vendor"), str(ROOT / "virtualfg.cpp"), "-ldl", "-o", str(temporary)]
    subprocess.run(command, check=True)
    temporary.replace(OUTPUT / "VirtualFG.cti")
    print(OUTPUT / "VirtualFG.cti")


if __name__ == "__main__":
    main()
